INSERT INTO COSTUMER (ID_COSTUMER, FIRST_NAME, LAST_NAME) VALUES (SQ_COSTUMER.NEXTVAL, 'Kaue', 'Carbonari');


INSERT INTO ACCOUNT (ID_ACCOUNT, ID_COSTUMER, EXPIRED_DATE) VALUES (SQ_ACCOUNT.NEXTVAL, 1, NULL);